// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPIProject.Models;

namespace WeatherAPIProject.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherAPIProject.Models.Weather", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forcast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HighTemperature")
                        .HasColumnType("real");

                    b.Property<float>("LowTemperature")
                        .HasColumnType("real");

                    b.HasKey("City");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            City = "chennai",
                            Date = new DateTime(2021, 5, 21, 20, 23, 8, 36, DateTimeKind.Local).AddTicks(3967),
                            Forcast = "sunny",
                            HighTemperature = 32f,
                            LowTemperature = 17f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
